# Generated by Django 6.0.3 on 2026-03-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notecategory_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
