# Generated by Django 6.0.3 on 2026-03-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_financeaccount_balance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeaccount',
            name='include_in_dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financeaccount',
            name='type',
            field=models.CharField(choices=[('bank', 'Bank'), ('e_wallet', 'E-Wallet'), ('cash', 'Tunai'), ('credit_card', 'Kartu Kredit'), ('paylater', 'Paylater'), ('investment', 'Investasi'), ('other', 'Lainnya')], default='bank', max_length=20),
        ),
    ]
