# Generated by Django 6.0.3 on 2026-03-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_financeaccount_include_in_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeaccount',
            name='due_day',
            field=models.IntegerField(blank=True, help_text='Tanggal jatuh tempo (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='statement_day',
            field=models.IntegerField(blank=True, help_text='Tanggal cetak statement (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installments',
            field=models.IntegerField(default=1, help_text='Jumlah cicilan (1x, 3x, dst)'),
        ),
    ]
